version: "3.7"
services:
  backend:
    container_name: backend
    build: .
    ports:
      - 3000:3001
    networks:
      - processor-network  # Define the network here
    depends_on:
      minio:
        condition: service_healthy

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2021-07-12T02-44-53Z
    networks:
      - processor-network
    volumes:
      - minio-storage:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: jhuly
      MINIO_ROOT_PASSWORD: jhuly1234
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  processor-network:
    driver: bridge

volumes:
  minio-storage:






